import { formatNumber } from "./formatters";
import type { ControlDefinition, ControlState } from "../types";

export const DEFAULT_CONTROLS: ControlState = {
  repulsion: 350,
  idealLength: 80,
  strength: 0.1,
  linkK: 0.02,
  boundaryK: 0.5,
  overlapK: 0.8,
  parentOverlapK: 0.2,
  boundaryPadding: 3,
  gravity: 0.01,
  damping: 0.96,
  step: 0.75,
  maxSpeed: 5,
  iterations: 6,
};

export const CONTROL_DEFINITIONS: ControlDefinition[] = [
  {
    key: "repulsion",
    label: "Repulsion",
    description: "모든 노드 쌍이 서로 밀어내는 기본 힘입니다.",
    min: 50,
    max: 1600,
    step: 10,
    format: (value) => formatNumber(value, 0),
    group: "primary",
  },
  {
    key: "idealLength",
    label: "Edge length",
    description: "링크가 유지하려는 목표 거리입니다.",
    min: 40,
    max: 200,
    step: 5,
    format: (value) => formatNumber(value, 0),
    group: "primary",
  },
  {
    key: "strength",
    label: "Edge strength",
    description: "링크가 끌어당기거나 미는 강도입니다.",
    min: 0.02,
    max: 0.4,
    step: 0.01,
    format: (value) => formatNumber(value, 2),
    group: "primary",
  },
  {
    key: "linkK",
    label: "Parent link",
    description: "부모-자식 스프링 강도입니다.",
    min: 0.005,
    max: 0.08,
    step: 0.005,
    format: (value) => formatNumber(value, 3),
    group: "primary",
  },
  {
    key: "boundaryK",
    label: "Boundary push",
    description: "자식이 부모 경계를 넘어갈 때 안으로 밀어넣는 힘입니다.",
    min: 0.1,
    max: 2,
    step: 0.1,
    format: (value) => formatNumber(value, 2),
    group: "primary",
  },
  {
    key: "overlapK",
    label: "Node overlap",
    description: "노드가 겹칠 때 추가로 분리하는 힘입니다.",
    min: 0.2,
    max: 2,
    step: 0.1,
    format: (value) => formatNumber(value, 2),
    group: "advanced",
  },
  {
    key: "parentOverlapK",
    label: "Parent overlap",
    description: "부모 경계가 겹칠 때 분리하는 힘입니다.",
    min: 0.2,
    max: 2,
    step: 0.1,
    format: (value) => formatNumber(value, 2),
    group: "advanced",
  },
  {
    key: "boundaryPadding",
    label: "Boundary padding",
    description: "부모 경계에 추가되는 여유 간격입니다.",
    min: 0,
    max: 40,
    step: 2,
    format: (value) => formatNumber(value, 0),
    group: "advanced",
  },
  {
    key: "gravity",
    label: "Gravity",
    description: "노드를 중심으로 끌어당기는 힘입니다.",
    min: 0,
    max: 0.08,
    step: 0.002,
    format: (value) => formatNumber(value, 3),
    group: "advanced",
  },
  {
    key: "damping",
    label: "Damping",
    description: "값이 높을수록 진동과 흔들림이 줄어듭니다.",
    min: 0.6,
    max: 0.99,
    step: 0.01,
    format: (value) => formatNumber(value, 2),
    group: "advanced",
  },
  {
    key: "step",
    label: "Step size",
    description: "틱마다 가속도를 얼마나 적용할지 정합니다.",
    min: 0.3,
    max: 2,
    step: 0.1,
    format: (value) => formatNumber(value, 1),
    group: "advanced",
  },
  {
    key: "maxSpeed",
    label: "Max speed",
    description: "속도가 과도해지는 것을 제한합니다.",
    min: 2,
    max: 20,
    step: 1,
    format: (value) => formatNumber(value, 0),
    group: "advanced",
  },
  {
    key: "iterations",
    label: "Iterations per frame",
    description: "반복 횟수가 많을수록 부드럽지만 CPU를 더 씁니다.",
    min: 1,
    max: 20,
    step: 1,
    format: (value) => formatNumber(value, 0),
    group: "advanced",
  },
];

export const PRIMARY_CONTROLS = CONTROL_DEFINITIONS.filter(
  (control) => control.group === "primary"
);

export const ADVANCED_CONTROLS = CONTROL_DEFINITIONS.filter(
  (control) => control.group === "advanced"
);
